/*
Generated by Yara-Rules
On 22-11-2023
*/

include "url.yara"
include "ip.yara"
include "interestingStr.yara"
include "crypto_signatures.yara"
include "email.yara"
include "key.yara"
include "passwd.yara"
include "phone.yara"
include "weak_password_hashes.yara"